services:
  ginmapper-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    environment:
      - R_ENVIRON_USER=/ginmappeR-API-server/.Renviron

  gintegrator-web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - ginmapper-api
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80